# site settings
title: Laura Ait Braham
subtitle: Information & UX Architect
email: laura.aitbraham@outlook.com
description: Portfolio of Laura Ait braham Information & UX Architect.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Laura Ait Braham
street_address: Chauss√©e de Charleroi 116
city: Brussels
state: BE
zip_code: 1000
country: Belgium

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings

linkedin_url: https://www.linkedin.com/in/loneska/

# build settings
markdown: kramdown

sass:
style: compressed
